USE MealBuddy;

insert into dietary_preferences (preference_id, name) values (1, 'Paleo');
insert into dietary_preferences (preference_id, name) values (2, 'Dairy-Free');
insert into dietary_preferences (preference_id, name) values (3, 'Nut Allergy');
insert into dietary_preferences (preference_id, name) values (4, 'Keto');
insert into dietary_preferences (preference_id, name) values (5, 'Vegetarian');
insert into dietary_preferences (preference_id, name) values (6, 'Kosher');
insert into dietary_preferences (preference_id, name) values (7, 'Paleo');
insert into dietary_preferences (preference_id, name) values (8, 'Keto');
insert into dietary_preferences (preference_id, name) values (9, 'Keto');
insert into dietary_preferences (preference_id, name) values (10, 'Gluten-Free');
insert into dietary_preferences (preference_id, name) values (11, 'Vegan');
insert into dietary_preferences (preference_id, name) values (12, 'Kosher');
insert into dietary_preferences (preference_id, name) values (13, 'Dairy-Free');
insert into dietary_preferences (preference_id, name) values (14, 'Gluten-Free');
insert into dietary_preferences (preference_id, name) values (15, 'Vegan');
insert into dietary_preferences (preference_id, name) values (16, 'Kosher');
insert into dietary_preferences (preference_id, name) values (17, 'Dairy-Free');
insert into dietary_preferences (preference_id, name) values (18, 'Paleo');
insert into dietary_preferences (preference_id, name) values (19, 'Vegan');
insert into dietary_preferences (preference_id, name) values (20, 'Gluten-Free');
insert into dietary_preferences (preference_id, name) values (21, 'Vegetarian');
insert into dietary_preferences (preference_id, name) values (22, 'Vegetarian');
insert into dietary_preferences (preference_id, name) values (23, 'Paleo');
insert into dietary_preferences (preference_id, name) values (24, 'Shellfish Allergy');
insert into dietary_preferences (preference_id, name) values (25, 'Gluten-Free');
insert into dietary_preferences (preference_id, name) values (26, 'Vegetarian');
insert into dietary_preferences (preference_id, name) values (27, 'Halal');
insert into dietary_preferences (preference_id, name) values (28, 'Keto');
insert into dietary_preferences (preference_id, name) values (29, 'Nut Allergy');
insert into dietary_preferences (preference_id, name) values (30, 'Vegetarian');
insert into dietary_preferences (preference_id, name) values (31, 'Dairy-Free');
insert into dietary_preferences (preference_id, name) values (32, 'Nut Allergy');
insert into dietary_preferences (preference_id, name) values (33, 'Dairy-Free');
insert into dietary_preferences (preference_id, name) values (34, 'Dairy-Free');
insert into dietary_preferences (preference_id, name) values (35, 'Keto');
insert into dietary_preferences (preference_id, name) values (36, 'Halal');
insert into dietary_preferences (preference_id, name) values (37, 'Nut Allergy');
insert into dietary_preferences (preference_id, name) values (38, 'Nut Allergy');
insert into dietary_preferences (preference_id, name) values (39, 'Shellfish Allergy');
insert into dietary_preferences (preference_id, name) values (40, 'Keto');
