insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (1, 'carrot', 'Baking', false, 'carrot', '2025-04-19');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (2, 'brussels sprouts', 'Meat', false, 'brussels sprouts', '2025-05-15');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (3, 'chicken', 'Spice', true, 'chicken', '2025-03-30');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (4, 'avocado', 'Grain', false, 'avocado', '2025-11-18');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (5, 'watercress', 'Spice', false, 'watercress', '2025-10-10');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (6, 'eggplant', 'Spice', true, 'eggplant', '2025-02-07');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (7, 'black beans', 'Baking', true, 'black beans', '2025-05-11');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (8, 'pasta', 'Grain', true, 'pasta', '2025-04-05');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (9, 'turnip', 'Meat', true, 'turnip', '2025-10-23');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (10, 'cauliflower', 'Spice', false, 'cauliflower', '2025-07-12');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (11, 'cucumber', 'Dairy', false, 'cucumber', '2025-07-10');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (12, 'chicken', 'Dairy', true, 'chicken', '2025-11-27');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (13, 'artichoke', 'Dairy', true, 'artichoke', '2025-09-08');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (14, 'black beans', 'Baking', false, 'black beans', '2025-11-20');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (15, 'broccoli', 'Spice', true, 'broccoli', '2025-11-24');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (16, 'rhubarb', 'Meat', false, 'rhubarb', '2025-02-11');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (17, 'okra', 'Baking', true, 'okra', '2025-03-06');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (18, 'carrot', 'Meat', true, 'carrot', '2025-06-07');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (19, 'brussels sprouts', 'Produce', true, 'brussels sprouts', '2025-06-01');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (20, 'tempeh', 'Produce', false, 'tempeh', '2025-03-07');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (21, 'corn', 'Produce', false, 'corn', '2025-12-03');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (22, 'beef', 'Produce', true, 'beef', '2025-03-23');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (23, 'quinoa', 'Produce', true, 'quinoa', '2025-10-25');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (24, 'corn', 'Spice', false, 'corn', '2024-12-26');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (25, 'tofu', 'Baking', true, 'tofu', '2025-02-06');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (26, 'radish', 'Grain', false, 'radish', '2025-02-23');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (27, 'garlic', 'Baking', false, 'garlic', '2025-05-23');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (28, 'avocado', 'Grain', false, 'avocado', '2025-11-26');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (29, 'carrot', 'Dairy', false, 'carrot', '2025-06-22');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (30, 'radish', 'Dairy', true, 'radish', '2025-02-05');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (31, 'onion', 'Grain', true, 'onion', '2025-01-12');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (32, 'chickpeas', 'Meat', false, 'chickpeas', '2025-05-08');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (33, 'watercress', 'Baking', true, 'watercress', '2025-06-23');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (34, 'bell pepper', 'Produce', true, 'bell pepper', '2025-05-06');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (35, 'parsnip', 'Dairy', true, 'parsnip', '2024-12-31');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (36, 'rhubarb', 'Meat', false, 'rhubarb', '2025-12-03');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (37, 'arugula', 'Baking', true, 'arugula', '2025-06-27');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (38, 'celery', 'Produce', true, 'celery', '2025-08-14');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (39, 'rice', 'Spice', false, 'rice', '2025-07-27');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (40, 'black beans', 'Grain', true, 'black beans', '2025-05-15');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (41, 'cucumber', 'Grain', false, 'cucumber', '2025-01-29');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (42, 'mushroom', 'Grain', true, 'mushroom', '2025-09-07');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (43, 'bell pepper', 'Meat', false, 'bell pepper', '2025-05-02');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (44, 'pasta', 'Grain', false, 'pasta', '2025-07-03');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (45, 'parsnip', 'Spice', false, 'parsnip', '2025-08-11');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (46, 'bell pepper', 'Produce', true, 'bell pepper', '2025-03-09');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (47, 'broccoli', 'Meat', false, 'broccoli', '2025-11-12');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (48, 'cheese', 'Grain', true, 'cheese', '2025-04-08');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (49, 'bell pepper', 'Spice', false, 'bell pepper', '2025-04-30');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (50, 'watercress', 'Dairy', true, 'watercress', '2025-06-01');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (51, 'sweet potato', 'Dairy', false, 'sweet potato', '2024-12-25');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (52, 'broccoli', 'Spice', false, 'broccoli', '2024-12-23');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (53, 'garlic', 'Meat', false, 'garlic', '2025-07-30');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (54, 'potato', 'Meat', false, 'potato', '2025-04-20');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (55, 'cabbage', 'Meat', true, 'cabbage', '2025-01-26');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (56, 'pasta', 'Baking', false, 'pasta', '2025-04-19');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (57, 'pepper', 'Grain', true, 'pepper', '2025-07-05');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (58, 'bell pepper', 'Produce', false, 'bell pepper', '2025-01-18');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (59, 'spinach', 'Produce', false, 'spinach', '2025-09-04');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (60, 'kale', 'Baking', true, 'kale', '2025-03-21');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (61, 'pumpkin', 'Produce', true, 'pumpkin', '2024-12-14');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (62, 'corn', 'Grain', true, 'corn', '2025-04-09');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (63, 'beets', 'Grain', true, 'beets', '2025-09-13');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (64, 'mushroom', 'Meat', false, 'mushroom', '2025-04-08');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (65, 'okra', 'Grain', false, 'okra', '2025-08-03');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (66, 'asparagus', 'Dairy', true, 'asparagus', '2025-06-02');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (67, 'onion', 'Dairy', true, 'onion', '2025-04-20');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (68, 'radish', 'Grain', true, 'radish', '2025-11-16');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (69, 'cauliflower', 'Dairy', true, 'cauliflower', '2025-10-28');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (70, 'pepper', 'Meat', true, 'pepper', '2025-10-16');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (71, 'tofu', 'Dairy', false, 'tofu', '2025-06-30');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (72, 'celery', 'Dairy', false, 'celery', '2025-09-22');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (73, 'spinach', 'Produce', false, 'spinach', '2025-08-26');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (74, 'pumpkin', 'Dairy', true, 'pumpkin', '2024-12-12');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (75, 'radish', 'Grain', false, 'radish', '2025-08-24');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (76, 'endive', 'Grain', true, 'endive', '2025-07-12');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (77, 'cucumber', 'Dairy', true, 'cucumber', '2025-07-04');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (78, 'seitan', 'Spice', false, 'seitan', '2025-08-23');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (79, 'asparagus', 'Spice', true, 'asparagus', '2025-02-12');
insert into ingredients (ingredient_id, ingredient_name, category, is_active, standardized_name, last_modified) values (80, 'quinoa', 'Produce', false, 'quinoa', '2025-05-29');
