insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (1, 'Eggs Benedict', 'easy', 152);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (2, 'Ribs', 'medium', 133);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (3, 'Veggie Omelet', 'medium', 45);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (4, 'Chili', 'hard', 151);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (5, 'Shepherd''s Pie', 'medium', 143);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (6, 'Shrimp Scampi', 'medium', 91);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (7, 'Fish and Chips', 'easy', 11);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (8, 'Veggie Omelet', 'easy', 133);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (9, 'Chicken Pot Pie', 'easy', 155);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (10, 'Roast Beef', 'medium', 29);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (11, 'Pancakes', 'medium', 76);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (12, 'Pad Thai', 'easy', 42);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (13, 'Ribs', 'easy', 148);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (14, 'Margherita Pizza', 'medium', 116);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (15, 'Spaghetti Bolognese', 'easy', 68);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (16, 'Chicken and Waffles', 'easy', 119);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (17, 'Pad Thai', 'medium', 112);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (18, 'Pulled Pork', 'hard', 173);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (19, 'Chicken and Waffles', 'easy', 167);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (20, 'Veggie Burger', 'medium', 68);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (21, 'Lentil Soup', 'hard', 67);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (22, 'Chicken Noodle Soup', 'easy', 135);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (23, 'Pasta Primavera', 'easy', 85);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (24, 'Fish and Chips', 'easy', 51);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (25, 'Roast Chicken', 'easy', 63);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (26, 'Brownies', 'medium', 157);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (27, 'Chili Con Carne', 'medium', 65);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (28, 'Chicken Noodle Soup', 'medium', 72);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (29, 'Tomato Soup', 'easy', 64);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (30, 'Roast Chicken', 'medium', 97);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (31, 'Pho', 'easy', 94);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (32, 'Guacamole', 'medium', 44);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (33, 'Quiche', 'medium', 179);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (34, 'Lamb Kofta', 'easy', 54);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (35, 'Chicken Noodle Soup', 'medium', 156);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (36, 'Pork Chops', 'easy', 134);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (37, 'Ribs', 'hard', 56);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (38, 'Chicken and Waffles', 'medium', 107);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (39, 'Pulled Pork', 'easy', 130);
insert into meals (meal_id, meal_name, difficulty, cooking_time_minutes) values (40, 'Shepherd''s Pie', 'medium', 83);
