insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (1, 3, 'Incorporate more superfoods', '2025-07-19', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (2, 37, 'Join a rowing team', '2024-12-08', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (3, 27, 'Try a new fitness app', '2025-10-18', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (4, 7, 'Incorporate more superfoods', '2025-04-18', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (5, 2, 'Cook meals at home more often', '2025-09-23', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (6, 2, 'Experiment with new recipes', '2025-06-23', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (7, 35, 'Try a new fitness challenge', '2024-12-31', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (8, 31, 'Cook with fresh herbs and spices', '2025-03-03', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (9, 3, 'Try a new sport or activity', '2025-03-19', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (10, 6, 'Experiment with meal delivery services', '2025-04-16', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (11, 18, 'Eat more plant-based meals', '2025-11-13', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (12, 39, 'Join a dance class', '2025-06-14', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (13, 6, 'Eat more seafood', '2025-09-10', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (14, 12, 'Eat more vegetables', '2024-12-14', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (15, 11, 'Incorporate more probiotics', '2025-02-24', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (16, 29, 'Incorporate more stretching', '2025-02-02', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (17, 3, 'Drink more water', '2025-02-13', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (18, 39, 'Practice mindful eating', '2025-11-23', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (19, 37, 'Try intermittent fasting', '2025-08-11', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (20, 9, 'Experiment with meal delivery services', '2025-09-22', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (21, 23, 'Try high-intensity interval training', '2025-02-19', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (22, 15, 'Practice meditation or mindfulness', '2025-08-14', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (23, 5, 'Eat more fiber-rich foods', '2025-10-31', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (24, 21, 'Limit processed foods', '2025-12-01', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (25, 6, 'Join a food subscription box', '2025-03-20', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (26, 5, 'Try a cleanse or detox', '2025-01-07', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (27, 41, 'Focus on core strength', '2025-06-13', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (28, 5, 'Join a rowing team', '2025-08-25', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (29, 6, 'Join a rowing team', '2025-08-14', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (30, 33, 'Try a new workout routine', '2024-12-16', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (31, 40, 'Join a hiking group', '2025-06-08', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (32, 29, 'Try high-intensity interval training', '2025-06-27', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (33, 25, 'Try a cleanse or detox', '2024-12-13', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (34, 23, 'Experiment with meal replacements', '2025-04-02', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (35, 24, 'Limit late-night snacking', '2025-02-23', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (36, 16, 'Increase daily steps', '2025-03-08', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (37, 18, 'Cook meals at home more often', '2025-02-14', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (38, 36, 'Try intermittent fasting', '2025-02-07', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (39, 24, 'more frequent meals', '2025-08-14', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (40, 22, 'Focus on flexibility and mobility', '2025-05-21', false);
