insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (1, 29, 'Total bifurcated capability', '2025-03-22', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (2, 25, 'Triple-buffered client-driven portal', '2025-06-08', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (3, 15, 'Devolved fault-tolerant contingency', '2025-01-08', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (4, 36, 'Organized systemic moratorium', '2025-04-14', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (5, 13, 'Customer-focused solution-oriented focus group', '2025-04-14', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (6, 23, 'Persevering methodical database', '2025-07-31', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (7, 22, 'Future-proofed systematic infrastructure', '2025-09-16', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (8, 11, 'Automated eco-centric instruction set', '2025-05-09', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (9, 40, 'Versatile heuristic access', '2025-02-22', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (10, 19, 'Automated 24 hour leverage', '2025-03-21', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (11, 18, 'Total methodical open architecture', '2024-12-14', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (12, 34, 'Configurable intangible parallelism', '2025-11-07', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (13, 26, 'Compatible next generation secured line', '2024-12-30', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (14, 27, 'User-centric intangible task-force', '2025-11-19', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (15, 29, 'Programmable human-resource circuit', '2025-03-13', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (16, 32, 'Vision-oriented needs-based interface', '2025-01-02', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (17, 17, 'Enterprise-wide homogeneous initiative', '2024-12-09', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (18, 33, 'Face to face intangible architecture', '2024-12-20', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (19, 13, 'Operative systematic matrix', '2024-12-08', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (20, 14, 'Extended impactful internet solution', '2025-01-22', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (21, 39, 'Down-sized 6th generation functionalities', '2025-08-08', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (22, 29, 'De-engineered 4th generation attitude', '2025-04-25', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (23, 35, 'Down-sized dedicated productivity', '2025-08-23', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (24, 4, 'Distributed didactic project', '2025-08-25', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (25, 39, 'Cloned clear-thinking firmware', '2025-10-16', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (26, 17, 'Innovative mobile throughput', '2025-06-18', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (27, 2, 'Reactive multi-state interface', '2025-01-09', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (28, 29, 'Streamlined content-based open system', '2025-08-09', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (29, 4, 'Managed grid-enabled capacity', '2024-12-20', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (30, 32, 'Diverse context-sensitive Graphic Interface', '2025-10-23', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (31, 1, 'Profit-focused web-enabled frame', '2025-09-27', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (32, 39, 'Face to face cohesive knowledge base', '2025-04-13', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (33, 44, 'Total clear-thinking emulation', '2025-06-27', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (34, 41, 'Business-focused cohesive orchestration', '2024-12-11', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (35, 29, 'Digitized system-worthy policy', '2025-01-07', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (36, 20, 'Optimized national strategy', '2025-11-12', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (37, 15, 'Face to face holistic adapter', '2025-03-26', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (38, 23, 'Synchronised bandwidth-monitored frame', '2025-04-08', false);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (39, 27, 'Programmable impactful benchmark', '2025-02-07', true);
insert into user_goals (goal_id, user_id, goal_description, target_date, is_active) values (40, 9, 'Horizontal client-server workforce', '2025-09-05', true);
